version: '3.8'
services:
  user-service:
    build: ./backend/user-service
    container_name: user-service
    ports:
      - "5001:5001"

  product-service:
    build: ./backend/product-service
    container_name: product-service
    ports:
      - "5002:5002"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - user-service
      - product-service

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - user-service
      - product-service
y